### ISSUE TITLE
Date not getting updated

### ISSUE THREAD

**Issue by unownone** [Ajit594/Weather-App#1]
# Summary
The date seems to be static. Needs to be dynamically updated as per client's location/time.

**Comment by unownone** [comment]
# The reason : 
This is happening because at first the weather data is hardcoded. Hence we should actually try to use page on load listener instead.

```   // Add a event listener that waits for the page to be loaded
  window.addEventListener("load", (event) => {
    console.log("page is fully loaded"); 
    /*Now we can update the weather*/
    getResults("Kolkata");
  });
```

This snippet can be added to make sure that user gets updated weather everytime weather is loaded. 

# Going over:
- We can also ask the user's browser for the location info by using [browser location api](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API) .

- Another thing can be done : Introduce a loading animation everytime the `getResults()` function is being loaded . Check how to do it here : [CSS Loader](https://www.w3schools.com/howto/howto_css_loader.asp)

**Comment by Ajit594** [comment]
completed
