### ISSUE TITLE
The `dateBuilder()` function may be replaced by inbuilt functionability

### ISSUE THREAD

**Issue by unownone** [Ajit594/Weather-App#2]
# Summary
The `scripts.js` contains a `dateBuilder()` that supposedly converts the `datetime` to a string . But you can do that using the inbuild `.toDateString()` function.

To use : 
```
var a = new Date();
console.log(a.toDateString()); // Prints out 'Mon Jan 02 2023'
```

This should make it easier for you to avoid bugs and reinventing the wheel.

**Comment by Ajit594** [comment]
completed
